/**
 * Represents a raw SQL expression snippet generated by dialect-aware functions.
 */
export class SqlFragment {
  constructor(public readonly text: string) {}

  public toString(): string {
    return this.text;
  }
}

function toExpr(val: unknown): string {
  if (val instanceof SqlFragment) return val.text;
  if (typeof val === 'string') {
    if (!val.includes(' ') && !val.includes('(') && !val.includes('.')) {
      return `"${val}"`;
    }
    return val;
  }
  return String(val);
}

/**
 * Cross-dialect database functions builder providing typed SQL expressions.
 */
export class RdbmsFunctionBuilder {
  // ── String Functions ────────────────────────────────────────────────────────

  public lower(col: unknown): SqlFragment {
    return new SqlFragment(`LOWER(${toExpr(col)})`);
  }

  public upper(col: unknown): SqlFragment {
    return new SqlFragment(`UPPER(${toExpr(col)})`);
  }

  public trim(col: unknown): SqlFragment {
    return new SqlFragment(`TRIM(${toExpr(col)})`);
  }

  public length(col: unknown): SqlFragment {
    return new SqlFragment(`LENGTH(${toExpr(col)})`);
  }

  public concat(...items: unknown[]): SqlFragment {
    return new SqlFragment(`CONCAT(${items.map(toExpr).join(', ')})`);
  }

  public substring(col: unknown, start: number, length?: number): SqlFragment {
    if (length !== undefined) {
      return new SqlFragment(`SUBSTRING(${toExpr(col)}, ${start}, ${length})`);
    }
    return new SqlFragment(`SUBSTRING(${toExpr(col)}, ${start})`);
  }

  public replace(col: unknown, search: string, replacement: string): SqlFragment {
    return new SqlFragment(`REPLACE(${toExpr(col)}, '${search}', '${replacement}')`);
  }

  // ── Math Functions ──────────────────────────────────────────────────────────

  public abs(val: unknown): SqlFragment {
    return new SqlFragment(`ABS(${toExpr(val)})`);
  }

  public round(val: unknown, decimals = 0): SqlFragment {
    if (decimals === 0) return new SqlFragment(`ROUND(${toExpr(val)})`);
    return new SqlFragment(`ROUND(${toExpr(val)}, ${decimals})`);
  }

  public ceil(val: unknown): SqlFragment {
    return new SqlFragment(`CEIL(${toExpr(val)})`);
  }

  public floor(val: unknown): SqlFragment {
    return new SqlFragment(`FLOOR(${toExpr(val)})`);
  }

  public power(base: unknown, exp: unknown): SqlFragment {
    return new SqlFragment(`POWER(${toExpr(base)}, ${toExpr(exp)})`);
  }

  public sqrt(val: unknown): SqlFragment {
    return new SqlFragment(`SQRT(${toExpr(val)})`);
  }

  // ── Date & Time Functions ───────────────────────────────────────────────────

  public now(): SqlFragment {
    return new SqlFragment('NOW()');
  }

  public currentDate(): SqlFragment {
    return new SqlFragment('CURRENT_DATE');
  }

  public currentTime(): SqlFragment {
    return new SqlFragment('CURRENT_TIME');
  }

  // ── Conditional & Aggregate Functions ───────────────────────────────────────

  public coalesce(...items: unknown[]): SqlFragment {
    return new SqlFragment(`COALESCE(${items.map(toExpr).join(', ')})`);
  }

  public nullif(val1: unknown, val2: unknown): SqlFragment {
    return new SqlFragment(`NULLIF(${toExpr(val1)}, ${toExpr(val2)})`);
  }

  public count(col: unknown = '*'): SqlFragment {
    return new SqlFragment(col === '*' ? 'COUNT(*)' : `COUNT(${toExpr(col)})`);
  }

  public sum(col: unknown): SqlFragment {
    return new SqlFragment(`SUM(${toExpr(col)})`);
  }

  public avg(col: unknown): SqlFragment {
    return new SqlFragment(`AVG(${toExpr(col)})`);
  }

  public min(col: unknown): SqlFragment {
    return new SqlFragment(`MIN(${toExpr(col)})`);
  }

  public max(col: unknown): SqlFragment {
    return new SqlFragment(`MAX(${toExpr(col)})`);
  }
}

/**
 * Dialect-aware RDBMS functions namespace (`fn`).
 */
export const fn = new RdbmsFunctionBuilder();

/**
 * Alias for `fn`.
 */
export const rdbms = fn;
