import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/quickstart', 'getting-started/database-providers'],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsed: false,
      items: ['core/dbcontext', 'core/entities-and-models', 'core/migrations'],
    },
    {
      type: 'category',
      label: 'Querying & LINQ',
      collapsed: false,
      items: [
        'querying/linq-fluent-api',
        'querying/pagination',
        'querying/relations-and-includes',
        'querying/aggregations-and-grouping',
      ],
    },
    {
      type: 'category',
      label: 'Advanced & Enterprise',
      collapsed: false,
      items: [
        'advanced/transactions',
        'advanced/stored-procedures',
        'advanced/locking',
        'advanced/vector-embeddings',
        'advanced/idempotency-and-outbox',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
  ],
};

export default sidebars;
